### ISSUE TITLE
visibility triggerbox problem

### ISSUE THREAD

**Issue by abs3nce** [noter-org/noter-client#114]
the triggerbox or hitbox is wide as the whole page, it is just a minor bug but could be fixed 
![image](https://user-images.githubusercontent.com/48967189/111003988-72381100-8388-11eb-8d1e-d4addf63f015.png)

**Comment by FajsiEx** [comment]
Will be fixed in the note viewer redesign in the next major update

**Comment by FajsiEx** [comment]
Fixed with the new header in 0.7.1 and 0.7.2
